name: Periodic health check

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 21 29 3 *'
    

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed app
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://sparkling-dream-9673.fly.dev/|https://sparkling-dream-9673.fly.dev/health
